version: '3.8'

services:
  python:
    build:
      context: ./src/python
      dockerfile: Dockerfile
    container_name: python_benchmark

  nodejs:
    build:
      context: ./src/nodejs
      dockerfile: Dockerfile
    container_name: nodejs_benchmark
  
  php:
    build:
      context: ./src/php
      dockerfile: Dockerfile
    container_name: php_benchmark
