# Usa una imagen base de PHP
FROM php:8.1-cli

# Crea y establece el directorio de trabajo
WORKDIR /app

# Copia el código fuente al contenedor
COPY . .

# Define el comando por defecto
CMD ["php", "main.php"]
